In [41]:
import pandas as pd

In [71]:
data = pd.read_csv('E:\\DataScience\\Data\\train.csv')

In [72]:
data=data[:15000]

In [73]:
data.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,...,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,1.500000e+04,15000.000000
mean,15050.804667,-1530.582800,33.227933,85.032080,74.257806,125.182164,5.422334,9.504842,0.954000,1.214000,...,3.835666,0.846944,7.384718,5.222968,17.443456,2.764760,37.241744,31.028344,1.172893e+05,0.040333
std,8697.547004,39129.142108,12.857333,1957.637064,351.951292,573.789577,128.375757,204.548879,59.312936,64.570459,...,250.351428,65.633760,552.511052,377.584395,618.107091,176.490267,1144.463989,1020.196556,1.747104e+05,0.196746
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.486360e+03,0.000000
25%,7533.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.821145e+04,0.000000
50%,15026.500000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.073964e+05,0.000000
75%,22551.500000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.194740e+05,0.000000
max,30168.000000,235.000000,102.000000,210000.000000,12888.030000,15182.460000,7904.220000,11073.570000,6600.000000,6600.000000,...,22217.130000,6643.290000,63317.190000,42767.160000,44990.490000,18928.590000,78561.150000,78561.150000,9.792857e+06,1.000000

In [60]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import train_test_split

In [74]:
feature = data.drop(columns='TARGET')

In [75]:
target = data.TARGET
target.value_counts()

0    14395
1      605
Name: TARGET, dtype: int64

In [76]:
x_train,y_train,x_test,y_test = train_test_split(feature,target)

In [77]:
vt = VarianceThreshold(threshold=0) #removing constant features

In [78]:
vt.fit_transform(x_train)

array([[1.55960000e+04, 2.00000000e+00, 2.60000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.49155650e+05],
       [9.72000000e+03, 2.00000000e+00, 2.50000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 8.40287400e+04],
       [8.95900000e+03, 2.00000000e+00, 4.00000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 6.41253000e+04],
       ...,
       [1.33120000e+04, 2.00000000e+00, 2.30000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.17310979e+05],
       [2.87900000e+04, 2.00000000e+00, 2.30000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 2.01984900e+05],
       [8.12500000e+03, 2.00000000e+00, 2.60000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 8.45250000e+04]])

In [79]:
x_train.columns[vt.get_support()]

Index(['ID', 'var3', 'var15', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult1',
       'imp_op_var39_comer_ult3', 'imp_op_var40_comer_ult1',
       'imp_op_var40_comer_ult3', 'imp_op_var40_efect_ult1',
       'imp_op_var40_efect_ult3',
       ...
       'saldo_medio_var29_ult3', 'saldo_medio_var33_hace2',
       'saldo_medio_var33_hace3', 'saldo_medio_var33_ult1',
       'saldo_medio_var33_ult3', 'saldo_medio_var44_hace2',
       'saldo_medio_var44_hace3', 'saldo_medio_var44_ult1',
       'saldo_medio_var44_ult3', 'var38'],
      dtype='object', length=292)

In [80]:
x_train[x_train.columns[vt.get_support()]]

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
7751,15596,2,26,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,149155.650000
4858,9720,2,25,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84028.740000
4459,8959,2,40,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64125.300000
14008,28126,2,19,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,341692.470000
4719,9439,5,57,0.0,300.0,300.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40518.210000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1599,3170,2,29,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47579.280000
9841,19789,2,39,2400.0,90.3,1517.34,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,460055.100000
6630,13312,2,23,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016
14317,28790,2,23,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,201984.900000
4053,8125,2,26,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84525.000000

In [81]:
x_train = x_train[x_train.columns[vt.get_support()]]

In [82]:
x_train.shape

(11250, 292)

In [83]:
vt_q = VarianceThreshold(threshold=0.2)# removing quasi constant features
vt_q.fit_transform(x_train)

array([[1.55960000e+04, 2.00000000e+00, 2.60000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.49155650e+05],
       [9.72000000e+03, 2.00000000e+00, 2.50000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 8.40287400e+04],
       [8.95900000e+03, 2.00000000e+00, 4.00000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 6.41253000e+04],
       ...,
       [1.33120000e+04, 2.00000000e+00, 2.30000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.17310979e+05],
       [2.87900000e+04, 2.00000000e+00, 2.30000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 2.01984900e+05],
       [8.12500000e+03, 2.00000000e+00, 2.60000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 8.45250000e+04]])

In [84]:
x_train.columns[vt_q.get_support()]

Index(['ID', 'var3', 'var15', 'imp_ent_var16_ult1', 'imp_op_var39_comer_ult1',
       'imp_op_var39_comer_ult3', 'imp_op_var40_comer_ult1',
       'imp_op_var40_comer_ult3', 'imp_op_var40_efect_ult1',
       'imp_op_var40_efect_ult3',
       ...
       'saldo_medio_var29_ult3', 'saldo_medio_var33_hace2',
       'saldo_medio_var33_hace3', 'saldo_medio_var33_ult1',
       'saldo_medio_var33_ult3', 'saldo_medio_var44_hace2',
       'saldo_medio_var44_hace3', 'saldo_medio_var44_ult1',
       'saldo_medio_var44_ult3', 'var38'],
      dtype='object', length=183)

In [86]:
x_train = x_train[x_train.columns[vt_q.get_support()]]

In [88]:
x_train.shape

(11250, 183)